edition = "2018"
merge_imports = true
format_strings = true
format_macro_matchers = true
max_width = 120
normalize_comments = true
report_todo = "Always"
report_fixme = "Always"
spaces_around_ranges = true
use_try_shorthand = true
format_doc_comments = true
match_arm_blocks = false
color = "Always"
normalize_doc_attributes = true
