sudo: false
cache: cargo
language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: beta
    - rust: nightly
  fast_finish: true

jobs:
  include:
    - stage: rustfmt
      before_script: rustup component add rustfmt
      script: cargo fmt -- --check
    - stage: clippy
      before_script: rustup component add clippy
      script: cargo clippy --all-targets --all-features -- -D warnings
    - stage: test
      script: cargo test --all-targets --all-features
    - stage: doc
      script: cargo doc --all --all-features
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local-dir: target/doc
        on:
          branch: master
      rust: nightly
    - stage: coverage
      before_script:
        - cargo install grcov -f
        - export CARGO_INCREMENTAL=0
        - export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads"
      script:
        - zip -0 ccov.zip `find . \( -name "*.gc*" \) -print`;
        - grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore-dir "/*" > lcov.info;
        - bash <(curl -s https://codecov.io/bash) -f lcov.info;
      rust: nightly

stages:
  - rustfmt
  - clippy
  - test
  - doc
  - coverage
