sudo: false
cache: cargo
language: rust

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

script: cargo test --all-targets --all-features

jobs:
  include:
    - name: rustfmt
      stage: check
      rust: stable
      before_script: rustup component add rustfmt
      script: cargo fmt -- --check
    - name: clippy
      stage: check
      rust: stable
      before_script: rustup component add clippy
      script: cargo clippy --all-targets --all-features -- -D warnings
    - stage: test
      rust: stable
    - stage: test
      rust: beta
    - stage: test
      rust: nightly
    - name: docs
      stage: util
      rust: stable
      script: cargo doc --all --all-features
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local-dir: target/doc
        on:
          branch: master
    - name: coverage
      stage: util
      rust: nightly
      before_script:
        - cargo install grcov -f
        - export CARGO_INCREMENTAL=0
        - export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads"
      before_cache:
        - zip -0 ccov.zip `find . \( -name "*.gc*" \) -print`;
        - >
            grcov ccov.zip -s . -t lcov --llvm --branch
            --ignore-not-existing
            --ignore-dir "/*"
            --ignore-dir "*/examples/**"
            --ignore-dir "*/tests/**"
            --ignore-dir "**/tests.rs"
            > lcov.info;
        - bash <(curl -s https://codecov.io/bash) -f lcov.info;

stages:
  - check
  - test
  - util
