sudo: false
cache:
  - ccache
  - cargo
language: rust
rust:
  - stable
  - beta
  - nightly

env:
  - RUSTFLAGS="-C link-dead-code"

addons:
  apt:
    packages:
      - binutils-dev
      - libcurl4-openssl-dev
      - zlib1g-dev
      - libdw-dev
      - libiberty-dev
      - cmake
      - gcc

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_script:
  - rustup component add clippy
script:
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo test
before_cache:
  - git clone https://github.com/SimonKagstrom/kcov
  - cd kcov
  - cmake ..
  - make install -j2
  - cd ..
  - |
    for file in target/debug/tgbot-*;
      do [ -x "${file}" ] || continue;
      mkdir -p "target/cov/$(basename $file)";
      kcov --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/$(basename $file)" "$file";
    done
  - bash <(curl -s https://codecov.io/bash)
