[package]
name = "carapax"
version = "0.1.0"
authors = ["Ross Nomann <rossnomann@protonmail.com>"]
edition = "2018"
readme = "README.md"
license = "MIT"
documentation = "https://docs.rs/carapax"
repository = "https://github.com/tg-rs/carapax"

[badges]
travis-ci = { repository = "tg-rs/carapax", branch = "master" }

[dependencies]
failure = "0.1"
futures = "0.1"
log = "0.4"
tgbot = { git = "https://github.com/tg-rs/tgbot", rev = "76964a7" }

[dev-dependencies]
dotenv = "0.13"
env_logger = "0.6"
serde_json = "1.0"
tokio = "0.1"
