[package]
name = "tgbot"
description = "A Telegram Bot library"
version = "0.3.0"
authors = ["Ross Nomann <rossnomann@protonmail.com>"]
edition = "2018"
readme = "README.md"
license = "MIT"
documentation = "https://docs.rs/tgbot"
repository = "https://github.com/tg-rs/tgbot"

[badges]
travis-ci = { repository = "tg-rs/tgbot", branch = "master" }
codecov = { repository = "tg-rs/tgbot" }

[dependencies]
derive_more = "0.14"
failure = "0.1"
futures = "0.1"
hyper = "0.12"
hyper-proxy = "0.5"
hyper-socks2 = "0.2"
hyper-tls = "0.3"
log = "0.4"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
tokio = "0.1"
tokio-sync = "0.1.3"
tokio-timer = "0.2"
typed-headers = "0.1"
url = "1.7"

[dev-dependencies]
dotenv = "0.13"
env_logger = "0.6"
