[package]
name = "carapax-ratelimit"
description = "Rate limit handler for carapax"
version = "0.1.0"
authors = ["Ross Nomann <rossnomann@protonmail.com>"]
edition = "2018"
readme = "README.md"
license = "MIT"
documentation = "https://docs.rs/carapax-ratelimit"
repository = "https://github.com/tg-rs/carapax-ratelimit"

[badges]
travis-ci = { repository = "tg-rs/carapax-ratelimit", branch = "master" }

[dependencies]
carapax = { git = "https://github.com/tg-rs/carapax", rev = "78895bc" }
nonzero_ext = "0.1"
ratelimit_meter = "4.0"
