[package]
name = "carapax"
description = "A Telegram Bot Framework"
version = "0.1.0"
authors = ["Ross Nomann <rossnomann@protonmail.com>"]
edition = "2018"
readme = "README.md"
license = "MIT"
documentation = "https://docs.rs/carapax"
repository = "https://github.com/tg-rs/carapax"

[badges]
travis-ci = { repository = "tg-rs/carapax", branch = "master" }
codecov = { repository = "tg-rs/carapax" }

[dependencies]
anymap = "0.12.0"
failure = "0.1.5"
futures = "0.1.23"
log = "0.4.6"
shellwords = "1.0.0"
tgbot = { git = "https://github.com/tg-rs/tgbot", rev = "7759363" }
tokio-executor = "0.1.5"

[dev-dependencies]
dotenv = "0.13.0"
env_logger = "0.6.0"
serde_json = "1.0.25"
tokio = { version = "0.1.7", default-features = false }
