[package]
name = "carapax"
description = "A Telegram Bot Framework"
version = "0.2.0"
authors = ["Ross Nomann <rossnomann@protonmail.com>"]
edition = "2018"
readme = "README.md"
license = "MIT"
documentation = "https://docs.rs/carapax"
repository = "https://github.com/tg-rs/tg-rs"

[dependencies]
anymap = "0.12.0"
failure = "0.1.5"
futures = "0.1.23"
log = "0.4.6"
regex = "1.0.5"
shellwords = "1.0.0"
tgbot = { path = "../tgbot" }
tokio-executor = "0.1.5"

[dev-dependencies]
dotenv = "0.13.0"
env_logger = "0.6.0"
serde_json = "1.0.25"
tokio = { version = "0.1.7", default-features = false }
